/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ContextMixin } from "../ContextMixin";

export class ContextMixin__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ContextMixin {
    return new Contract(address, _abi, signerOrProvider) as ContextMixin;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x5de83298",
        type: "bytes32",
      },
    ],
    name: "c_0x5de83298",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];
