/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IStateReceiver } from "../IStateReceiver";

export class IStateReceiver__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStateReceiver {
    return new Contract(address, _abi, signerOrProvider) as IStateReceiver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onStateReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
