import '../styles/globals.css';

import type { AppProps } from 'next/app';
import Head from 'next/head';
import Link from 'next/link';
import { Provider } from 'next-auth/client';
import React from 'react';

import Web3ContextProvider from '../contexts/web3Context';

const DefaultLayout = ({ children }) => children;

import { useRouter } from 'next/dist/client/router';

import Button from '../components/Button';
import styles from '../styles/Home.module.css';

function MyApp({ Component, pageProps }: AppProps) {
  const Layout = (Component as any).Layout || DefaultLayout;
  const router = useRouter();
  return (
    <>
      <Head>
        <title>FairDrop by 0xEssential</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,800;1,500;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Provider>
        <Web3ContextProvider>
          <Layout>
            <div className="container">
              <main className="main">
                <div className="header">
                  <div className="titleContainer">
                    <h1 className="title">
                      <em>FairDrop</em> 🎡
                    </h1>

                    <p className="description">
                      A proof-of-concept for fair NFT drops
                    </p>

                    <p>
                      <a
                        href="https://github.com/0xessential/fair-drop"
                        target="_blank"
                        rel="noreferrer"
                      >
                        Github
                      </a>{' '}
                      • Etherscan • Polygonscan
                    </p>
                  </div>
                  <div className="buttonContainer">
                    {router.pathname == '/mint' ? (
                      <Link href="/" passHref>
                        <Button>Home</Button>
                      </Link>
                    ) : (
                      <Link href="/mint" passHref>
                        <Button>Try it</Button>
                      </Link>
                    )}
                  </div>
                </div>
                <Component {...pageProps} />
              </main>
            </div>
          </Layout>
        </Web3ContextProvider>
      </Provider>
    </>
  );
}
export default MyApp;
