import Head from 'next/head';
import React, { useState } from 'react';
import Modal from 'react-modal';

import Button from '../components/Button';
import Drop from '../components/Drop';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>FairDrop by 0xEssential</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,800;1,500;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.titleContainer}>
            <h1 className={styles.title}>
              <em>FairDrop</em> 🎡
            </h1>

            <p className={styles.description}>
              A proof-of-concept for fair NFT drops
            </p>

            <p>
              <a
                href="https://github.com/0xessential/fair-drop"
                target="_blank"
                rel="noreferrer"
              >
                Github
              </a>{' '}
              • Etherscan • Polygonscan
            </p>
          </div>
          <div className={styles.buttonContainer}>
            <Button onClick={() => setModalOpen(true)}>Try it</Button>
          </div>
        </div>
        <div className={styles.article}>
          {/* <Drop /> */}
          <p>
            At{' '}
            <a
              href="https://twitter.com/0xessential"
              target="_blank"
              rel="noreferrer"
            >
              0xEssential
            </a>{' '}
            we&apos;ve been learning from other NFT collectible drops to
            determine the best way to release our collection{' '}
            <a href="https://wrasslers.com" target="_blank" rel="noreferrer">
              Wrasslers
            </a>
            . We appreciate that projects like{' '}
            <a href="https://artblocks.io/" target="_blank" rel="noreferrer">
              ArtBlocks
            </a>{' '}
            and{' '}
            <a
              href="https://www.parallel.life/"
              target="_blank"
              rel="noreferrer"
            >
              Parallel
            </a>{' '}
            are exploring different models to reduce the gas wars that happen on
            popular drops, and have been impressed by projects like{' '}
            <a
              href="https://forgettenrunes.com/"
              target="_blank"
              rel="noreferrer"
            >
              Forgotten Runes Wizard&apos;s Cult
            </a>{' '}
            who used and{' '}
            <a
              href="https://twitter.com/cryppadotta/status/1420372022790483979"
              target="_blank"
              rel="noreferrer"
            >
              shared some best practices
            </a>
            . We&apos;re also excited about some platforms our friends are
            working on to help solve similar issues, like{' '}
            <a href="https://niftyroyale.com/" target="_blank" rel="noreferrer">
              Nifty Royale
            </a>{' '}
            and{' '}
            <a href="https://chestr.io/" target="_blank" rel="noreferrer">
              Chestr
            </a>
            . We think we can add something to the conversation by offering this
            idea and reference implementation to the community.
          </p>
          <p>
            0xEssential is committed to building open source developer tools for
            NFT projects. We are primarily focused on inheritable contracts that
            provide metaverse portability and utility, but any time we build
            tools for ourselves, we like to share them back to the community - a
            rising tide lifts all boats⛵️
          </p>
          <p>
            Our ideal NFT drop is average user first - no FOMO or failed
            transactions, fewer bots. No drama, no whales minting 30% of supply,
            for better or worse. These are the key aspects of a{' '}
            <em>FairDrop</em>:
          </p>
          <ul>
            <li>
              <strong>Efficient</strong> - no more gas wars, and no performance
              issues related to pageloads.
            </li>
            <li>
              <strong>Timezone agnostic</strong> - crypto is global, and timed
              drops inevitably put someone at a disadvantage, while launch dates
              are too frequently missed.
            </li>
            <li>
              <strong>Distributed randomly</strong> - being the quickest to
              click and pumping gas is not the best way to decide who gets an
              NFT.
            </li>
            <li>
              <strong>Decentralized and Trustless</strong> - we should not be
              asking users to register with email, or using a centralized
              database and webserver to manage who can buy what.
            </li>
          </ul>

          <p>
            We took all of those requirements and built a system that uses
            raffles with a <em>right to buy</em> reward. Random winners get to
            mint NFTs at a fair floor price, wherever they are in the world,
            whether they&apos;re influencers, etherscan minters, bot makers, or
            MEV manipulators.
            <br />
          </p>
          <hr />
          <h2> 1. Register</h2>
          <h3>Address registers for drop on-chain</h3>
          <p>
            A user can register their interest in an NFT drop in a decentralized
            way. We use Polygon for registration to keep things cheap. A project
            can launch their list before release to build and gauge interest,
            while users know they have a fair chance to mint.
          </p>

          <h2>2. Raffle</h2>
          <h3>Totally fair random selection</h3>
          <p>
            Once a project is ready for launch we use Chainlink VRF to select a
            random list of eligible minters. These addresses can each mint{' '}
            <em>n</em> tokens, where <em>n x minters</em> is equal to available
            tokens. Addresses are passed to Ethereum mainnet for minting.
          </p>

          <h2>3. Redeem</h2>
          <h3>Chilled out and cheap mints</h3>
          <p>
            Eligible minting addresses have 24 hours to mint their tokens. They
            mint on Ethereum mainnet without the need for gas wars or staying up
            all night to catch a drop.
          </p>

          <h2>4. Repeat</h2>
          <h3></h3>
          <p>
            After 24 hours a new batch of eligible minters is selected for
            minting. Previous minters become ineligible and we select a new set
            of minters relative to remaining tokens.
          </p>
          <hr />

          <p>
            While there are certainly potential pitfalls and improvements to the
            implementation of this approach, we think these mechanics would be a
            huge win for NFT collectors without adding much of a burden to
            project developers. Note that this was hacked together quickly, and
            while we are testing it in production, this code is not audited or
            battle-tested at all.
          </p>
          <p>
            One issue with this approach is that it does not prevent bots from
            signing up thousands of addresses. Since registration is cheap in tx
            cost and onchain, there is not a great way to prevent this. We could
            require at least a small payment for registration, which might help,
            but adds complexity and might not be accepted by users. It is true
            that the bot owner would need to check each of their registered
            addresses for eligibility, and purchase through eligible addresses,
            but this can be done pretty easily too, and captchas or other
            web-based tools of course cannot prevent interacting with the
            contracts directly. In some ways we are forced to choose between
            decentralization and fairness. Parallel used email registration with
            a centralized server - this makes it a lot easier to prevent bots,
            but also introduces trust and the potential of censorship.
          </p>
          <p>
            Another area of concern is with a large number of addresses eligible
            to mint, transaction costs of passing these addresses back to L1
            might become too expensive. One alternative might be to sell users
            an ERC20 token on Polygon, allow the user to bridge that token to
            L1, and then accept that token as payment for minting an NFT - this
            might also help with the bot problem, where migrating an ERC20 token
            is a bit more complex of a process. Or mint NFTs on Polygon and
            allow users to migrate them to L1 if they choose.
          </p>
          <p>
            We don&apos;t have all of the answers but hope to kick off a
            conversation with the community! Thanks for reading, PRs welcome,
            and let us know your thoughts?
          </p>
          <hr />
          <iframe
            src="https://theconvo.space/embed/dt?url=https%3A%2F%2Ffairdrop.0xessential.com%2F&threadId=fairdrop-discussion&theme=light"
            allowTransparency={true}
            width="100%"
            style={{ border: 'none', margin: '24px 0' }}
          >
            Comments
          </iframe>
        </div>
      </main>
      <Modal
        isOpen={modalOpen}
        closeTimeoutMS={500}
        onRequestClose={() => setModalOpen(false)}
      >
        <Drop />
      </Modal>
    </div>
  );
}
