import Head from 'next/head';
import React from 'react';

import Drop from '../components/Drop';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FairDrop by 0xEssential</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,800;1,500;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1 className={styles.title}>FairDrop 🎡</h1>

          <p className={styles.description}>
            A proof-of-concept for fairer NFT drops from 0xEssential
          </p>

          <p>
            <a
              href="https://github.com/0xessential/fair-drop"
              target="_blank"
              rel="noreferrer"
            >
              Github
            </a>{' '}
            • Etherscan • Polygonscan
          </p>
        </div>
        <div className={styles.article}>
          <Drop />
          <p>
            At{' '}
            <a
              href="https://twitter.com/0xessential"
              target="_blank"
              rel="noreferrer"
            >
              0xEssential
            </a>{' '}
            we&apos;ve been learning from other NFT collectible drops to
            determine the best way to release our collection{' '}
            <a href="https://wrasslers.com" target="_blank" rel="noreferrer">
              Wrasslers
            </a>
            . We appreciate that projects like{' '}
            <a href="https://artblocks.io/" target="_blank" rel="noreferrer">
              ArtBlocks
            </a>{' '}
            and{' '}
            <a
              href="https://www.parallel.life/"
              target="_blank"
              rel="noreferrer"
            >
              Parallel
            </a>{' '}
            are exploring different models to reduce the gas wars that happen on
            popular drops, and have been impressed by projects like{' '}
            <a
              href="https://forgettenrunes.com/"
              target="_blank"
              rel="noreferrer"
            >
              Forgotten Runes Wizard&apos;s Cult
            </a>{' '}
            who used and{' '}
            <a
              href="https://twitter.com/cryppadotta/status/1420372022790483979"
              target="_blank"
              rel="noreferrer"
            >
              shared some best practices
            </a>
            . We&apos;re also excited about some platforms our friends are
            working on to help solve similar issues, like{' '}
            <a href="https://niftyroyale.com/" target="_blank" rel="noreferrer">
              Nifty Royale
            </a>{' '}
            and{' '}
            <a href="https://chestr.io/" target="_blank" rel="noreferrer">
              Chestr
            </a>
            . We think we can add something to the conversation by offering this
            idea and reference implementation to the community.
          </p>
          <p>
            0xEssential is committed to building open source developer tools for
            NFT projects. We are primarily focused on inheritable contracts that
            provide metaverse portability and utility, but any time w&apos;re
            building tools for ourselves, w&apos;ll also share them back to the
            community - a rising tide lifts all boats.
          </p>
          <p>Our ideal for a more fair NFT drop approach solution is: </p>
          <ul>
            <li>
              <strong>Efficient</strong> - no more gas wars, and no performance
              issues related to pageloads.
            </li>
            <li>
              <strong>Timezone agnostic</strong> - crypto is global, and timed
              drops inevitably put someone at a disadvantage, while launch dates
              are too frequently missed.
            </li>
            <li>
              <strong>Distributed randomly</strong> - being the quickest to
              click and pumping gas is not the best way to decide who gets an
              NFT.
            </li>
            <li>
              <strong>Decentralized and Trustless</strong> - we should not be
              asking users to register with email, or using a centralized
              database and webserver to manage who can buy what.
            </li>
          </ul>

          <p>
            The solution w&apos;ve come up with is a system where users can
            register their interest for an NFT drop. We use the Polygon chain
            for this registration flow to keep things cheap and efficient. When
            the project is ready to release, we use Chainlink VRF to select
            eligible minter addresses from the list of registrants. We then use
            Polygon&apos;s State Transfer to pass the list of eligible minter
            addresses to the Ethereum mainnet contract.
          </p>

          <p>
            This way we select eligible minters in an onchain and provably
            random manner. The number of eligible minters should of course be
            less than the remaining mints - if each user can mint 3 tokens, and
            you have 9,999 tokens in your drop, then you would select 3,333
            addresses per tranche.
          </p>
          <p>
            Eligible minters will then have 24 hours to visit the minting site
            and mint their tokens. There won&apos;t be any gas wars as every
            eligible minter has 24 hours to mint tokens that are set aside for
            them.
          </p>
          <p>
            If an eligible minter does not mint during their eligibility window,
            then after 24 hours we can select a new tranche of eligible minters
            who will also have 24 hours to purchase. Rinse and repeat until we
            are done.
          </p>

          <p>
            To demonstrate how this works, we deployed our contracts and built a
            dapp that you are currently viewing! W&apos;re selling 3 NFTs that
            you can think of as badges for committing to doing fairer drops. You
            can register for your opportunity to buy below, and check back later
            to see if you&apos;ve won the raffle for a chance to mint one of our
            NFTs. W&apos;ve priced the NFTs just to cover the cost of contract
            deployment.
          </p>
        </div>
      </main>
    </div>
  );
}
